apiVersion: v1
kind: Service
metadata:
  name: homelab-api
  namespace: homelab-api
  labels:
    app.kubernetes.io/name: homelab-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: homelab-api
  ports:
    - name: http
      port: 80
      targetPort: http
