k3s_version: "v1.31.5+k3s1"
k3s_token: "{{ vault_k3s_token }}"
k3s_flannel_iface: "eno2"
k3s_disable:
  - servicelb

ansible_ssh_common_args: >-
  -o ProxyJump=root@46.225.217.139

metallb_version: "v0.14.5"
metallb_ip_pool_name: "homelab-pool"
metallb_l2adv_name: "homelab-l2"

# IMPORTANT: must be outside DHCP
metallb_addresses:
  - "192.168.50.240-192.168.50.250"

cert_manager_version: "v1.14.6"

lets_encrypt_email: "wlodzimierrr@gmail.com"
lets_encrypt_server: "https://acme-v02.api.letsencrypt.org/directory"
# for testing without rate limits:
# lets_encrypt_server: "https://acme-staging-v02.api.letsencrypt.org/directory"

clusterissuer_name: "letsencrypt-http01"

# Traefik settings
traefik_ingress_class: "traefik"
acme_ingress_class: "traefik"
